BUG: Fix mapclassify #88
pysal/mapclassify pull request #89
Opened 2020-10-25 17:57 UTC by jeffcsauer

This is a PR to fix https://github.com/pysal/mapclassify/issues/88. Changes have been made to [`_classify()` function](https://github.com/jeffcsauer/mapclassify/blob/7aad6fca0521cc29c64d43a1618dabd16a1ea965/mapclassify/classifiers.py#L632-L637) such that it now checks to see if max `y` and min `y` are equal (across multiple classifiers, not just `EqualInterval`). If max `y` and min `y` are equal there is now a `ValueError` with the following description: 

`Minimum and maximum of input data are equal, cannot create bins.`

There may be a better error message...

PR as part of the October 2020 PySAL Sprint.

2020-10-25 18:18 UTC, slumnitz approved these changes
success! 👍

2020-10-25 18:57 UTC, sjsrey requested changes

2020-10-25 18:57 UTC, sjsrey commented on mapclassify/classifiers.py
>          """
This looks good and handles this edge case.

I might add some unit tests.

2020-11-23 00:30 UTC, sjsrey commented
Should be passing now that 3.6 is excluded on windows with #94

2020-11-23 00:31 UTC, merged