[WIP] 2.4.0 Release
pysal/mapclassify pull request #97
Opened 2020-12-12 20:03 UTC by sjsrey

2020-12-12 20:04 UTC, jGaboardi approved these changes

2020-12-12 20:31 UTC, jGaboardi commented
Seems like maybe `numba` or a dependency of `numba` is causing issues with environment solve for `conda-incubator/setup-miniconda` on Ubuntu in Python 3.6 & 3.7.

2020-12-12 20:43 UTC, martinfleis approved these changes

2020-12-13 20:09 UTC, slumnitz requested changes
Thank you @sjsrey for adding documentation.
I saw the classify doc-string still needed a small update. I added all classifiers in https://github.com/sjsrey/mapclassify/pull/3 and re-ran the notebook. Looks great otherwise!

2020-12-14 03:23 UTC, merged